excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://Giuzzo.github.io
title: MyChok | WeMake | Giorgio Nuzzo <img src="https://raw.githubusercontent.com/Giuzzo/Giuzzo.github.io/master/link_img/banner.jpg"/>
email: giorgio.nuzzo@gmail.com
author: Giorgio Nuzzo
description: Report del lavoro svolto nel fablab milanese WeMake nell'ambito del progetto MyChok
paginate: 10
google_analytics: 